
@class CMMVector, MMTabBarController, NSMutableArray, NSString, PreEnterWechatLogic, SvrErrorTipWindow, UIWindow;

@interface CAppViewControllerManager : NSObject{
    UIWindow *m_window;
    NSMutableArray *m_arrViewController;
    NSMutableArray *m_arrTabBarBaseViewController;
    unsigned long m_uCurrentTabViewIndex;
    CMMVector *m_vecViewController;
    BOOL m_bFromReg;
    BOOL m_isChangingTheme;
    BOOL m_isInBackground;
    SvrErrorTipWindow *m_svrErrorTipWindow;
    PreEnterWechatLogic *m_PreEnterWechatLogic;
    MMTabBarController *m_tabbarController;
}

+ (id)topViewControllerOfWindow:(id)arg1;
+ (id)topMostController;
+ (id)getCurrentNavigationController;
+ (id)getTabBarController;
+ (id)getAppViewControllerManager;
+ (BOOL)hasEnterWechatMain;
@property(readonly, nonatomic) BOOL m_isInBackground; // @synthesize m_isInBackground;
//- (void).cxx_destruct;
- (id)formatCGFloat:(float)arg1;
- (void)printView:(id)arg1 withLevel:(int)arg2 buffer:(id)arg3;
- (void)didTakeSnapshot:(id)arg1;
- (id)getTabBarController;
- (void)onDataChangedWithAdded:(id)arg1 andChanged:(id)arg2 andDeleted:(id)arg3;
- (id)getEnteranceViewContoller;
- (void)onPatternLockLogicOperateSuccess;
- (void)onNotifyRemindMsg:(id)arg1;
- (void)setupUserInfoAndCategoryForNotification:(id)arg1 message:(id)arg2 username:(id)arg3;
- (void)OnShowPush:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)UIWindowDidResignKeyNotification:(id)arg1;
- (void)UIWindowDidBecomeKeyNotification:(id)arg1;
- (void)UIWindowDidBecomeHiddenNotification:(id)arg1;
- (void)UIWindowDidBecomeVisibleNotification:(id)arg1;
- (void)enterBackground;
- (void)enterForeground;
- (void)onPreQuit;
- (void)jumpToChat:(id)arg1 msgToLocate:(unsigned long)arg2;
- (void)JumpToViewController:(id)arg1;
- (void)HandleMoreJump:(id)arg1;
- (void)HandleFindFriendJump:(id)arg1;
- (void)HandleMainFrameJump:(id)arg1;
- (void)fixOnStatusBarClick;
- (id)getMainWindow;
- (void)changeLanguage;
- (void)refreshLanguage:(int)arg1;
- (void)refreshMainFrame;
- (void)refreshLanguage:(int)arg1 withChildScene:(id)arg2;
- (BOOL)isNowInRootViewController;
- (void)jumpToOfflinePay;
- (void)jumpToShareCard;
- (void)jumpToAlbum;
- (void)jumpToShake;
- (void)jumpToCameraScan:(int)arg1 showMainView:(BOOL)arg2;
- (void)jumpToCameraScan:(int)arg1;
- (void)jumpToURLShardBy3rdApp:(id)arg1;
- (BOOL)isChangingTheme;
- (void)onThemeChanged;
- (unsigned long)getCurTabBarIndex;
- (id)getTopViewController;
- (void)removeViewController:(id)arg1;
- (void)addViewController:(id)arg1;
- (void)removeViewFromRootViewController:(id)arg1;
- (void)addViewControllerToRootView:(id)arg1;
- (void)removeViewFromRootView:(id)arg1;
- (void)addViewToRootView:(id)arg1;
- (BOOL)isInStatusBarShowViewController;
- (unsigned long)getTotalUnReadCount;
- (void)closeMainFrame;
- (void)openMainFrame:(BOOL)arg1 showStyle:(id)arg2;
- (void)openFirstView;
- (void)OnMainFrameDoubleClicked:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)setAllTabBarItemEnabled:(BOOL)arg1;
- (void)newMessageByEnterpriseContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(BOOL)arg3 showSessionList:(BOOL)arg4 animated:(BOOL)arg5 extraInfo:(id)arg6;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 animated:(BOOL)arg3;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(BOOL)arg3;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(BOOL)arg3 animated:(BOOL)arg4 extraInfo:(id)arg5;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 showMainView:(BOOL)arg3 animated:(BOOL)arg4;
- (void)moveToTab:(int)arg1 showMainView:(BOOL)arg2;
- (void)moveToRootViewControllerForIndex:(int)arg1;
- (void)moveToRootViewController;
- (void)dismissToRootViewControllerForIndex:(int)arg1;
- (void)dismissToRootViewController;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (void)dealloc;
- (void)createMainFrameWithShowStyle:(id)arg1;
- (void)replaceTwoFile:(id)arg1 desFile:(id)arg2;
- (void)createMoreViewController;
- (void)createFindFriendViewController;
- (void)recreateFindFriendViewController;
- (void)createContactsViewController;
- (void)createNewMainFrameViewController;
- (id)getTabBarBaseViewController:(unsigned int)arg1;
- (id)getNewMainFrameViewController;
- (void)forceRedrawNavigationViewControllers:(id)arg1;
- (void)forceRedrawNavigationViewControllers;
- (void)forceRedrawNavigationBars;
- (id)initWithWindow:(id)arg1;
- (void)restartAllFailUploadFromLocalNotification;
- (void)reSendAllMsgFromNotificationDone;
- (void)resendAllFailMsgFromLocalNotification:(id)arg1;
- (BOOL)checkResentFailMsg:(id)arg1 isFromLaunch:(BOOL)arg2;
- (void)openView:(unsigned long)arg1 launchOptions:(id)arg2 isAppUpdated:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end
